pardeike/Harmony

- Harmony/ILCopying/ILInstruction.cs
As discussed on discord. Thanks for the tech support <3
> Empty constructor for type conversion exception

- Harmony/MethodPatcher.cs
- Harmony/Tools/AccessTools.cs
> Support for directly addressing parameters and fields by index

- Harmony/Internal/PatchFunctions.cs
- Harmony/Internal/PatchSorter.cs
- Harmony/Public/Patch.cs
- HarmonyTests/Patching/PatchAttributes.cs
- HarmonyTests/Patching/PatchSorting.cs
Should be ready to merge now.
Todo:
> Implementation of the new Patch sorting algorithm

- HarmonyTests/Patching/PatchSorting.cs
Hey, i just wanted to make sure that the new sorter is nice.
So i added a few more basic unit tests.
And yes, it is!! 👍 
Maybe you want the tests?
> Some basic sorter tests

- Harmony/Tools/AccessTools.cs
- HarmonyTests/Tools/Assets/AccessToolsClass.cs
- HarmonyTests/Tools/TestAccessTools.cs
Added overload that takes FieldInfo as an argument. Also added support for static fields.
Not sure what behavior you want for a version that takes in a fieldname. For now I left it as it was in the original.
> FieldRefAccess expansion

- README.md
Harmony is very popular among Unturned plugin developers
> Add Unturned to games list

- Harmony/Internal/MethodPatcher.cs
The exception came up a few times on the RimWorld discord. This should clear up some confusion.
> improve wording on exception for pass through postfix

- nuget.config
The last PR wasn't ready to be merged just yet as I was discussing a fix to the Azure Pipelines outage with Zamu on the Discord 😅 
~~Submitting this as a draft PR to see if any further ADOP-specific fixes will be needed before merging.~~
> Update nuget.config to also add nuget.org feed (Thanks, Azure)

- Harmony/Harmony.csproj
- HarmonyTests/HarmonyTests.csproj
Remove unnecessary DefineConstants in csprojs again
> Remove unnecessary DefineConstants in csprojs again

- Harmony/Internal/StructReturnBufferCheck.cs
> Use GetManagedSize from MonoMod.Utils to work around old mono bug

- Harmony/Tools/AccessTools.cs
- HarmonyTests/Tools/Assets/AccessToolsClass.cs
- HarmonyTests/Tools/TestAccessTools.cs
Based off https://gist.github.com/lbmaian/2369d6614a9e56ad2392254b4638d096 and discussion in discord
> Add AccessTools.MethodDelegate and basic unit tests

- Harmony/Tools/AccessTools.cs
Link to sample Travis CI (mono) that failed: https://travis-ci.org/github/pardeike/Harmony/jobs/697262488
I tried manually fetching the delegate constructor and invoking it (rather than using `Activator.CreateInstance`) but that still didn't work.
So I had to resort to using a DMD to create the ldftn delegate in a similar matter to how delegate injection is done. The main difference is that struct value boxing happens in the dmd.Invoke rather than in the DMD code itself. Although this is more expensive than simply calling the delegate constructor via reflection (including `Activator.CreateInstance`), this is still a one-time cost.
> Workaround mono issue on creating "non-virtual" closed instance delegates

- Harmony/Tools/AccessTools.cs
The following image is a screenshot from profiling the patch time in RogueTech, a heavily modded version of BattleTech.
As shown in the pic, `MakeDeepCopy` accounts for more than 90% of cpu time. The majority of the time is spent on getting the handler of `Add` method for types.
This PR is a simple optimization on this process by creating a dictionary for fast repetitive accesses.
This is the profiling data after the change.
Following is a comparison on memory usage,
Before,
After,
The difference mostly can attribute to transient memory allocation, and as the memory usage shown in the After change, the allocation for persistent memory is quite small. However, it would not hurt if Harmony can open an API for modloaders to clear the cache.
> Add handler cache for MakeDeepCopy

- Harmony/Documentation/Documentation.csproj
- Harmony/Harmony.csproj
- HarmonyTests/HarmonyTests.csproj
This is so net5 patching works properly.
> Update MonoMod.Common to 20.12.7.4

- README.md
Fix the broken link in the readme
> Fix link to 0x0ade's profile

- Harmony/Harmony.csproj
- ILRepack.targets
Also, do not copy the attributes when ILMerging, it's not required for the dependencies to work
> Added SourceLink support

- Harmony/Tools/Extensions.cs
> Allow OpCodes.Ldstr in LoadsConstant

- Harmony/Internal/MethodCreator.cs
Fixes/Handles the test cases introduced in #664
> Improve handling of mismatching __state types

- Harmony/Internal/MethodCreator.cs
- HarmonyTests/Patching/Arguments.cs
- HarmonyTests/Patching/Assets/ArgumentCases.cs
> Fix minor issue in __state variable handling; improve test case

- Harmony/Tools/FileLog.cs
- Make logging using custom LogWriter thread save
- Make logging Multiple-Process save by using FileShare
> Slightly adjust logging

- .github/workflows/test-build.yml
avoid building the whole solution for ReleaseRef
> Fix ReleaseRef build step

- Harmony/Internal/MethodCreator.cs
- improve `AddInfixes` with cleaner LINQ and modern syntax
- `git status --short`
> Refactor AddInfixes
