Harmony/ILCopying/Memory.cs, Harmony/Tools/DynamicTools.cs, HarmonyTests/HarmonyTests.csproj, HarmonyTests/Patching/Assets/PatchClasses.cs, HarmonyTests/Patching/StaticPatches.cs
Relevant: #2 
`DynamicMethod::CreateDynMethod` doesn't exist in the .NET Framework; instead, `DynamicMethod::GetMethodDescriptor` and `RuntimeHelper::_CompileMethod` do.
As `_CompileMethod` seems to float around with different signatures (can take either the `RuntimeMethodHandle` or its `IntPtr` `Value` as only argument), `PrepareDynamicMethod` takes both variants into account.
I still need to get a test case mod running; @llaughlin, it'd be nice if you could help testing this as you seem to already have a test case :)
Notes:
* I'm currently manually reformatting the code to fit your existing code style.  
* All tests are failing locally without a copied `0Harmony.dll`, which is why I set
```xml
<Private>True</Private>
```
in `HarmonyTests.csproj`. Some tests are still failing, f.e. the …
=> .NET Framework support

Harmony/ILCopying/Memory.cs, Harmony/Tools/DynamicTools.cs, HarmonyTests/HarmonyTests.csproj, HarmonyTests/Patching/Assets/PatchClasses.cs, HarmonyTests/Patching/StaticPatches.cs
Thanks to @Kittyfisto's work, Harmony is now functional on .NET Framework 4.6.2. I didn't notice the issues during the previous pull request.
Additionally, I've added a `TestMethod2` test case that tests patching instance methods. As @Kittyfisto noticed in #18, the .NET Framework is stricter and thus requires `DynamicMethod`s to always be static.
From my understanding, Harmony only cares about the target method's body (the method to jump into), not if the target `DynamicMethod` is static or not. Furthermore, I haven't noticed any issues with static methods mimicking instance method behavior. To me, it seems quite similar to how extension methods work.
=> Further .NET Framework support fixes

Harmony/Extras/MethodInvoker.cs, HarmonyTests/Extras/Assets/MethodInvokerClasses.cs, HarmonyTests/Extras/TestMethodInvoker.cs, HarmonyTests/HarmonyTests.csproj
MethodInvoker.Handler uses locals as a layer of indirection for the arguments, which is useful for reference types (`ref` and `out` parameters), but adds some overhead when invoking the method.
Recently, I've spent my time implementing `ref` support to the ReflectionHelper in MonoMod (offline .NET assembly patcher), but instead of using locals, I opted to operate on the stack. This means MonoMod's ReflectionHelper is now basically supporting everything Harmony's MethodInvoker does.
It's not as clear and took some time to figure out, but after benchmarking the results in MonoMod, it was visible that it's profitable: 
```
100000000 runs:
dmdNewBox (ReflectionHelper modified, immutable boxes): 36.5712269s
dmdMutable (ReflectionHelper, formerly called raw): 16.3218110s
dmdLocals …
```
=> Make MethodInvoker.Handler operate on stack instead of locals

Harmony/Attributes.cs, Harmony/MethodPatcher.cs
Fixes #51 
First I wanted to add a new field to PatchInfo/Patch but I changed my mind. If you have any design/optimization suggestions or you have any objections regarding current design tell me. Feel free to change the naming as well. I tried to follow your naming convention.
```csharp
[HarmonyPatch(typeof(Player))]
[HarmonyPatch("CastSpell")]
[HarmonyParameter("#d", "spellId")]
class ExamplePatch
{
// This has the higher priority than the one above
[HarmonyParameter("#d", "spellId")]
[HarmonyParameter("#c", "targetid")]
// Parameter attributes have the highest priority
public static void Prefix([HarmonyParameter("#d")] int spellId, int targetid)
{
}
// No need to do anything since we have added class-wide attribute
public static void Postfix(int spellId)
{
}
}
```
This also works when …
=> Added ability to give parameters your own name

Harmony/CodeInstruction.cs, HarmonyTests/HarmonyTests.csproj, HarmonyTests/IL/Instructions.cs
Previously if you were to call ToString on a `ldstr` instruction with a constant string that included format indices like `{1}`, then it would get passed directly to `string.Format`, causing an exception.
This PR removes the seemingly unnecessary `string.Format` call (as no other parameters are passed) and includes a test to cover `ToString()` exceptions.
=> Fix issue formatting ldstr operand

Harmony/Attributes.cs, Harmony/Extras/MethodInvoker.cs, Harmony/Harmony.csproj, Harmony/MethodPatcher.cs, Harmony/Tools/PatchTools.cs
Okay, this version should actually work.
I've changed the signatures _and_ redirected the constructors to a shared case to ensure correct parameters are always passed.
Note: **Every** variant with a `param` array needs an overload _without_ that parameter, so `HarmonyPatch()` like calls actually resolve to the `null`version of the overload instead of the 'empty array' version.
---
Closes #96
=> Add param array parameters to HarmonyPatchAttribute

Harmony/Attributes.cs, Harmony/HarmonyMethod.cs, Harmony/PatchFunctions.cs
The `priority` field in `HarmonyMethod` is currently misspelled `prioritiy`. This typo also occurs in the parameter name for the explicit `HarmonyPriority` constructor.
[This line](https://github.com/pardeike/Harmony/compare/master...ayan4m1:fix/priority-name?expand=1#diff-61f938e2025ec01f805d23e93979ad2cR17) may be a breaking change for downstream users, but the fix is dead simple.
Also, apologies as I am not intimately familiar with the codebase, but is there a reason why the public fields of `HarmonyMethod` are camelCase and not CamelCase?
=> Fix spelling of "priority" field name

Harmony/PatchProcessor.cs, Harmony/Tools/AccessTools.cs
Ambiguous matches that were caught now throw when there's no match and inform you where you screwed up.
Null originals now show the Harmony.ID rather than just the vague error of "original". Should people screw up their overloads or typo the target method, they can theoretically change their harmony ID to more easily find the offending patch.
=> slightly improved error reporting

Harmony/Tools/AccessCache.cs
Avoids potential System.ArgumentException when null method is added to the cache multiple times due to AccessTools failing to find method that fits the signature.
Not sure if that's the exact behavior you want to have or if throwing exception would be better.
=> Avoid System.ArgumentException

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/TestAccessTools.cs
Option to pass declaring type as object to FieldRef for cases where declaring type might be private nested type. Also check that FieldRef return type is actually assignable.
=> FieldRef FieldType check and option to ignore DeclaringType check

Harmony/Documentation/articles/patching-prefix.md, Harmony/Public/HarmonyInstance.cs
b3368e3 fixes a tabs vs spaces mistake I introduced in #167.
The argument exception we discussed on discord.
=> Doc fix + ArgumentException on null or empty id

Harmony/Internal/MethodPatcher.cs, HarmonyTests/Patching/Assets/PatchClasses.cs, HarmonyTests/Patching/DynamicMethodPatches.cs
I've also included a unit test which is what I've been using for reproduction.
Note that in `Assets.Class11` I've included an `int dummy` parameter, which is required to trigger failures that are fixed in MethodPatcher.cs line 234 and line 300.
I've tested this in both regular .NET 4.5 runtime and Unity 5.x which contains the old mono implementation. Fix on line 234 was only needed for the old mono runtime, it works fine without it on regular .NET.
I have not tested this on Unity 2017.3, however I believe the new mono runtime included with it would work, similar to the (more compliant) .NET implementation.  Unity 2018 and above do not apply as they ship mscorlib with the stubbed System.Reflection.Emit runtime.
=> Fixes for DynamicMethod patching

Harmony/Internal/DynamicTools.cs
This pull request fixes #208 .
There were two issues regarding return types of patched methods:
- If an enum has a base type of long/ulong it needs to be handled as a 64bit value type
(Solution: Use the enum's underlying type to decide what to do)
- A ulong also needs to be handled as 64bit like the long
=> Handle methods returning a ulong or an enum with base type long/ulong correctly

.travis.yml, Harmony.sln, Harmony/Harmony.csproj, HarmonyTests/HarmonyTests.csproj, HarmonyTests/IL/DynamicArgumentPatches.cs, appveyor.yml, azure-pipelines.yml
1. Update nugets to latest versions
2. Add Microsoft.NETFramework.ReferenceAssemblies nuget dependency for non-Windows builds
3. Update appveyor config:
1. Use 'Visual Studio 2019' image
2. Run dotnet test for all target frameworks except .NET Framework 3.5
3. Run nunit3-console for .NET Framework 3.5 with --inprocess flag, because Microsoft.NETFramework.ReferenceAssemblies doesn't include a build for .NET Framework 3.5 yet
4. Update travis config:
1. Use dotnet 3.0 and latest nunit3-console nuget
2. Run dotnet test for all target frameworks except .NET Framework 3.5
3. Run nunit3-console for .NET Framework 3.5 with --inprocess flag, because Microsoft.NETFramework.ReferenceAssemblies doesn't include a build for .NET Framework 3.5 yet
5. Update azure-pipelines to use 'windows-latest' …
=> Update nugets, try updating CI to run tests for all target frameworks

.travis.yml, HarmonyTests/IL/DynamicArgumentPatches.cs, HarmonyTests/ReversePatching/AttributeReversePatches.cs, HarmonyTests/ReversePatching/ReverseTranspiling.cs
* Fix DynamicArgumentPatches.SendingArguments unit test on mono (see #221 for the error)
* Don't enable Harmony.DEBUG in unit tests, allow linux CI to fail if it is enabled
=> Fix remaining unit testing issues (excluding netcoreapp3.0 issues)

Harmony/Internal/MethodCopier.cs, HarmonyTests/IL/TestMethodBodyReader.cs, HarmonyTests/Patching/Assets/PatchClasses.cs
Fix MethodBodyReader throwing error when parsing local var operand and no generator.
Add unit test.
In the future, there should be a way to publicly expose this functionality (something like `List<CodeInstruction> GetMethodInstructions(MethodBase method)`) along with caching.
=> Fix MethodBodyReader throwing error when parsing local var operand and no generator

.travis.yml, Harmony/Harmony.csproj, HarmonyTests/HarmonyTests.csproj, HarmonyTests/IL/TestMethodBodyReader.cs
* Add workaround .NET Framework 3.5 reference assemblies (fixes x-platform dotnet build)
* Update to non-preview Microsoft.NETFramework.ReferenceAssemblies
* Update comment on why dotnet test doesn't work for .NET Framework 3.5
* Fix copy&paste error in MethodBodyReader unit test
=> dotnet build now works cross-platform (but not dotnet test), misc

Harmony/Extras/MethodInvoker.cs, HarmonyTests/Extras/TestMethodInvoker.cs
Some background, continuing from the discussion on discord:
I was curious as to how and why the `directBoxValueAccess=false` logic in `MethodInvoker` works for by-ref value types. I learned the whole point of this mode is to avoid directly updating the boxed value in the arguments array, which could which be reflected in all existing references to that boxed value (not just in the arguments array), and to instead replace that boxed value in the arguments array with a "reboxed" value, such that updates to the boxed value are instead localized only to this reboxed value.
To illustrate the difference:
```cs
public static void TimesTwo(ref int x) => x *= 2;
...
var method = GetType().GetMethod(nameof(TimesTwo));
var handler = MethodInvoker.Handler(method, method.DeclaringType.Module, …
```
=> Fix rare MethodInvoker directBoxValueAccess=false bug where an inopportune GC can cause reboxed value address to become invalid

.travis.yml, Harmony/Harmony.csproj, HarmonyTests/HarmonyTests.csproj, appveyor.yml
* Update travis build to use dotnet 3.1.
* Include reference assemblies again to fix non-Windows .NET Framework targeting builds.
=> Update travis build to use dotnet 3.1

Harmony/Documentation/articles/patching-injections.md
The current documentation does not mention support for `__0`, `__1`, etc, as the patched method argument names. This change adds a little more detail on this.
Code pointer showing such support: https://github.com/pardeike/Harmony/blob/53f5182aef326863f9fdd5d4193df137f985ae28/Harmony/Internal/MethodPatcher.cs#L431
=> Update Argument Injection Documentation

.gitmodules, Harmony.sln, Harmony/Harmony.csproj, HarmonyTests/HarmonyTests.csproj, nuget.config
This PR simply replaces the MonoMod.Common submodule with signed prebuilt MonoMod.Common NuGet packages from the [MonoMod Azure Artifacts devbuild feed](https://dev.azure.com/MonoMod/MonoMod/_packaging?_a=feed&feed=DevBuilds) and updates the existing ILRepack rules to include it.
=> Remove MonoMod.Common submodule, use Azure devbuild NuGet feed

Harmony/Harmony.csproj, Harmony/Internal/MethodPatcher.cs, HarmonyTests/HarmonyTests.csproj
This PR simply updates MonoMod.Common to 20.2.2.1 and sets the OwnerType of the DynamicMethodDefinition generated in MethodPatcher.cs, in an effort to fix the "calling assembly" issue reported by FailedShack on Discord.
=> Set DynamicMethodDefinition.OwnerType

Harmony/Internal/MethodPatcher.cs
Commit f213218d30237cee09085ffe60cf6d0a94501b71 introduced a bug in which a method's original variables got defined after the temporary result variable and all other patch-related variables, resulting in (best case) the JITter throwing an `ExecutionEngineException` and (worst case) memory corruption in form of an uncatchable access violation.
This PR fixes the variable definition order.
=> Fix variable definition order: keep orig vars first

Harmony/Tools/Extensions.cs
Ldarg_s needs the operand cast to Byte, not int - InvalidCastException otherwise.
(There are probably more occurrences of this problem, but this is just the one I hit)
Example transpiler simply to catch the exception:
```cs
[HarmonyPatch(typeof(PlaceWorker_PreventInteractionSpotOverlap), nameof(PlaceWorker_PreventInteractionSpotOverlap.AllowsPlacing))]
public static class IgnoreInteractionSpotOverlap {
public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
{
foreach(var inst in instructions)
{ 
try
{
bool test = inst.IsLdarg(5);
}
catch (Exception e)
{
Log.Message($"- {inst}/{inst.operand.GetType()}");
Log.Message($"- {e}");
}
yield return inst;
}
}
}
```
results:
- ldarg.s 4/System.Byte
- `System.InvalidCastException: Specified cast is not valid. …
=> Fix CodeInstruction Extension IsLdarg for short-form operands

Harmony/Harmony.csproj, Harmony/Internal/CodeTranspiler.cs, Harmony/Internal/PatchFunctions.cs, Harmony/Internal/PatchTools.cs, Harmony/Public/CodeInstruction.cs, Harmony/Public/PatchClassProcessor.cs, Harmony/Tools/AccessTools.cs, HarmonyTests/HarmonyTests.csproj, HarmonyTests/Patching/Assets/PatchClasses.cs, HarmonyTests/Patching/Transpiling.cs
* Undo unnecessary exception stack trace preservation changes, though keep a `RethrowException` utility method
* Remove unnecessary `DefineConstants`
* Fix lazy enumerable transpilers running multiple times if transpiler uses exact same `CodeInstruction` type
=> Fix lazy enumerable transpilers running multiple times, undo unnecessary exception stack trace preservation changes

Harmony/Tools/Extensions.cs
`code.Is(opcode, operand)` is a shortcut for `code.opcode == opcode && code.OperandIs(operand)`
The `MemberInfo` overloads are just optimized versions for the common use case of comparing with types, fields, methods etc. (when the opcode isn't ldfld, call, etc. so the more specialized extension methods can't be used). They're hidden in IntelliSense to avoid user confusion.
=> Proposed Is extension method and optimized MemeberInfo Is/OperandIs overloads

Harmony/Harmony.csproj, HarmonyTests/HarmonyTests.csproj, azure-pipelines.yml, nuget.config
When using Harmony 2.0 from NuGet for .NET Core, Mono.Cecil and MonoMod.Common cannot be found. This is because:
- `PrivateAssets="All"` was permanently applied to the MonoMod.Common package reference, meaning that the nuspec in the nupkg didn't refer to it at all.
- Mono.Cecil is referenced via MonoMod.Common.
- MonoMod.Common was only available using the devbuild feed.
This PR makes MonoMod.Common a public dependency for the .NET Core (and possible future .NET Standard - if needed) builds of Harmony. .NET Framework support stays completely unchanged.
Beyond this PR, MonoMod.Common is now available on nuget.org - albeit as an unlisted package: https://www.nuget.org/packages/MonoMod.Common  
This means that Harmony can depend on it and anything depending on Harmony can now pull it in …
=> Make MonoMod.Common a public dependency for .NET Standard / Core

Harmony/Harmony.csproj, Harmony/Properties/AssemblyInfo.cs, HarmonyTests/HarmonyTests.csproj
This PR fixes #275 by updating MMC to 20.4.5.1 and adds `[assembly: InternalsVisibleTo("MonoMod.Utils.Cil.ILGeneratorProxy")]` to Harmony's `AssemblyInfo.cs`
=> Fix issue #275 - Update MMC and add missing InternalsVisibleTo

Harmony/Public/CodeInstruction.cs, Harmony/Tools/AccessTools.cs
This clarifies the `typeColonMethodname` argument and links to the official docs for the type name format, so users can look up edge cases like nested types.
=> Clarify 'typeColonMethodname' docs

Harmony/Internal/MethodPatcher.cs
Currently patch methods lose the namespace/type info, so you have error traces like this:
```
at StardewValley.Locations.MovieTheater..ctor() in ...
at load_Patch2()
```
This adds the type to the method name, so stack traces look like this instead:
```
at StardewValley.Locations.MovieTheater..ctor() in ...
at StardewValley.Game1.load_Patch2()
```
=> Include type in patched method names for stack traces

Harmony/Extras/MethodInvoker.cs, Harmony/Tools/AccessTools.cs
Convenience change for MethodInvoker
This is a binary-compatible change: https://github.com/ltrzesniewski/dotnet-runtime/blob/master/docs/coding-guidelines/breaking-change-rules.md#signatures (method signature unchanged, just adds the `ParamArrayAttribute` attribute to parameters arg)
=> Make FastInvokeHandler uses params for varargs

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/TestAccessTools.cs
Support interface method delegates and open instance delegates with interface instance.
Fix mono workaround's inability to access non-public delegate type.
Add more unit tests.
=> More AccessTools delegate work

Harmony/Internal/MethodPatcher.cs, Harmony/Public/Attributes.cs, Harmony/Tools/AccessTools.cs, HarmonyTests/Patching/Arguments.cs, HarmonyTests/Patching/Assets/PatchClasses.cs, HarmonyTests/Tools/Assets/AccessToolsClass.cs, HarmonyTests/Tools/TestAccessTools.cs
As discussed in discord...
- Implement virtual delegate injection
- Default to virtual calling
- `AccessTools.CreateDelegate` => `AccessTools.MethodDelegate`, `AccessTools.CreateHarmonyDelegate` => `AccessTools.HarmonyDelegate`
- `MethodInheritance.Virtual/None` => `MethodBinding.CallVirtually/Call`
- Add optional `instance` param to `AccessTools.HarmonyDelegate`
- Split up `AccessTools` delegate tests. This is done partly for organizational reasons (and to make room for more edge case tests), and partly to demonstrate mutability of passed non-struct instances.
- Improve some XML docs
=> More AccessTools/injected delegate work

Harmony/Internal/MethodPatcher.cs, Harmony/Public/Attributes.cs, Harmony/Public/HarmonyMethod.cs, Harmony/Tools/AccessTools.cs, HarmonyTests/Patching/Assets/PatchClasses.cs
Edited quote from discord:
I'm having second thoughts on the `MethodBinding` naming, since "binding" is an unfortunately overused term, even within delegates, e.g. bound/unbound delegates. And there's also the existing `System.Reflection.Binder` and `System.Runtime.Serialization.SerializationBinder` and `Microsoft.CSharp.RuntimeBinder.Binder` and `System.Runtime.CompilerServices.CallSiteBinder` classes, and that's not even getting into all the "data binding" stuff.
I think "dispatch" as suggested earlier is a better option, since it's far less overloaded of a term. Indeed dynamic dispatch is considered a specific type of dynamic/late binding (although the difference might be academic in C#, excluding Harmony patching; probably only relevant for languages that can add/remove/change methods …
=> More HarmonyDelegate tweaks

Harmony/Public/Harmony.cs
Exception example:
```
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
at System.Reflection.Assembly.GetTypes () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0
at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00000] in <e1f1ac2cbe0f4a33bf2c833b6962b66e>:0
```
=> Fix exception on patchall when optional dependencies are missing

Harmony/Public/Harmony.cs, Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/TestAccessTools.cs
Followup on #323
* For "invalid" assemblies that throw `ReflectionTypeLoadException`, `AccessTools.TypeByName/GetTypesFromAssembly` now returns/searches the successfully loaded types.
* Always use `Assembly.GetTypes()` rather than `Assembly.DefinedTypes.ToArray()`.
* Change `Harmony.PatchAll` to use `AccessTools.GetTypesFromAssembly` (followup on #324).
=> Fix AccessTools.TypeByName/GetTypesFromAssembly to not throw exception when there exist "invalid" assemblies

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/Assets/AccessToolsClass.cs, HarmonyTests/Tools/TestAccessTools.cs, HarmonyTests/Tools/TestFieldRefAccess.cs
Followup on #321
* Add `AccessTools.StructFieldRef` and `StructFieldRefAccess` for struct support.
* For existing `AccessTools.FieldRefAccess` and `AccessTools.StaticFieldRefAccess` methods, handle edge cases and have consistent error handling, as exhaustively documented via `TestFieldRefAccess`.
* Also fixes `AccessTools.FindIncludingBaseTypes` (and thus all the methods that rely on it) NRE on interface types and unknown members.
* Improve related XML docs and some code consistency.
These changes have tested for binary compatibility with versions before this change on:
* Mono runtime (.NET Framework 3.5+ equivalent)
* CLR 4 (.NET Framework 4+)
* CoreCLR (.NET Core 3+)
where "binary compatibility" here specifically means that any pre-change usage that results in an exception or crash (or …
=> AccessTools.*FieldRefAccess improvements, including struct support

Harmony/Documentation/articles/patching-edgecases.md, docs/articles/patching-edgecases.html
Expand the documentation for patching generic types based on information learned from Mono blog posts, documentation, and experimentation.
=> Expand documentation for patching generics

Harmony/Internal/HarmonySharedState.cs, Harmony/Internal/PatchTools.cs, Harmony/Internal/StructReturnBufferCheck.cs, Harmony/Tools/AccessTools.cs, Harmony/Tools/FileLog.cs
`HarmonySharedState`:
- A lock on a `const` string doesn't look safe (might be safe due to the interned string, but let's not bank on it), so locking on an explicit lock object.
- Also locking over the whole operation, rather than just on `GetState`.
`PatchTools`:
- Attributed `objectReferences` with `ThreadStatic`. Even though this Dictionary is only stored to and never read from, it still needs to be thread-safe: https://stackoverflow.com/a/33153868
`AccessTools`:
- Make `AccessTools.all`/`allDeclared` `static readonly`, with a note on why they're not `const` (would break binary compatibility). I'm making the probably safe assumption that no one ever sets these fields.
Other changes:
- Revert `StructReturnBuffer.sizes` back to `static readonly` now that tests are clearing it rather than …
=> More thread-safety

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/TestFieldRefAccess.cs
Revert `AccessTools.FieldRefAccess` methods' generic `T : class` constraint, moving it to a runtime check within the methods
Although the generic class constraint was binary compatible when `T` is directly a class,
it broke calls that passed an unconstrained type argument as `T`, e.g. generic wrapper methods that call `FieldRefAccess`.
=> Revert AccessTools.FieldRefAccess methods' generic T : class constraint

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/Assets/AccessToolsClass.cs, HarmonyTests/Tools/TestFieldRefAccess.cs
`FieldRef` now supports `F` = underlying integral type for `enum` field types
=> FieldRef now supports F = underlying integral type for enum field types

Harmony/Public/CodeInstruction.cs, Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/Assets/AccessToolsClass.cs, HarmonyTests/Tools/TestAccessTools.cs
Look at each commit separately.
First commit:
* Add `AccessTools.CreateInstance<T>()`
* Add unit tests that demonstrate `AccessTools.CreateInstance` currently only calls public parameterless constructors
Second commit:
* `AccessTools.CreateInstance` can now use non-public parameterless constructors
* Define internal `CodeInstruction` parameterless constructor
* `AccessTools.CreateInstance` also now invokes the `ConstructorInfo` rather than using `Activator.CreateInstance`; the former should be faster
=> AccessTools.CreateInstance improvements

Harmony/Public/HarmonyMethod.cs, HarmonyTests/Tools/Assets/AttributesClass.cs, HarmonyTests/Tools/TestAttributes.cs
When the HarmonyMethods for attributes are merged, Harmony considers that if the detail attribute field has a null value, it shouldn't be applied. This doesn't consider that the priority field defaults to -1, and causes it to be overridden if the HarmonyPriority attribute isn't merged last.
This is shown with 0b5867c32e23df54393a9d7ade907fe9da2f310b, which fails without the second commit also applied.
I think the proper solution would be to make priority a nullable int so it is caught by the existing if statements, but I *believe* this breaks API compat? Adding an exception to the ifs seemed like a safer option, so this PR does that instead.
=> Bugfix priority attribute

Directory.Build.props, Harmony/Internal/MethodCopier.cs
This PR updates MonoMod.Common and adds calls to the new `FixReflectionCacheAuto` method where necessary.
Please see [this Stardew Valley Modding API issue comment](https://github.com/Pathoschild/SMAPI/issues/722#issuecomment-880239368) for more information.  
TL;DR is that the XNA Framework depends on the order of `type.GetFields()` to stay consistent (even MSDN says to *not* do so!), but calling `ResolveField` (and also possibly other member-resolving methods) changes the order that the .NET Framework caches for subsequent calls.  
**This was also a problem with Harmony 1.X**, but it was merely avoided by the fact that the XNA Framework was the first thing to call `.GetFields()` on the affected type *before* the "incorrect" order got cached. Pathoschild confirmed experimentally that …
=> Update MonoMod, add FixReflectionCacheAuto calls

Harmony/Internal/Memory.cs
The previous attempt to fix the short method issue was allocating memory
from a dynamic code manager. However, the detour was overwriting memory
inside the global code manager.
This fix calls the dynamically generated padding method, which forces
Mono to allocate a JIT trampoline for the padding method. Even though
the padding function is stored in a dynamic code manager, the JIT
trampoline is allocated from the global code manager. Shortly
afterwards, patching the short function will overwrite the padding
method's JIT trampoline, instead of the next important thing that is
stored in the global code manager.
=> Fix issue #414: add a sacrificial JIT trampoline after short methods

Harmony/Tools/AccessTools.cs
I'm not 100% sure, but seems like ABI compat is preserved.
Testing out an app that was compiled against a older version of a lib with no contravariance, then running it against a newer version with added contravariance seems to work.
=> Provide contravariance on FieldRef delegate

Directory.Build.props, Harmony/Internal/HarmonySharedState.cs, Harmony/Public/Harmony.cs, HarmonyTests/Extras/RetrieveOriginalMethod.cs
Adds a unit test demonstrating, and then fixes a bug where the `MethodInfo` reference returned from a StackTrace is not equivalent to the reference which gets returned from `HarmonyLib.MethodPatcher:CreateReplacement`.
This relies on an update from MonoMod.Common which attempts to source the original method from method which is returned from the stack trace. This can then be used to find the pointer which represents the start of the method, which can be used to identify which original method it is referring to.
Let me know if you would like me to squash changes into a single commit, or clean up any details of the implementation.
=> Fixes HarmonySharedState:GetOriginal  

Harmony/Harmony.csproj, Harmony/Public/Patch.cs, Harmony/Public/PatchJsonConverter.net5.cs, Harmony/Public/UtfJsonReaderExtensions.net5.cs, HarmonyTests/HarmonyTests.csproj
Starting with I believe .NET 5, `BinaryFormatters` aren't supported by default.  To use them, you have to enable them in your .csproj with the following.
```xml
<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
```
For security reasons, Microsoft is recommending that support for this be removed in applications as outlined here - https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide
The two places I can see this occurring (at least in the project I am using) are in the following methods
https://github.com/pardeike/Harmony/blob/4c6eaed10c3fd5133b8ee5805e1919103ca812ba/Harmony/Public/Patch.cs#L41-L47
https://github.com/pardeike/Harmony/blob/4c6eaed10c3fd5133b8ee5805e1919103ca812ba/Harmony/Public/Patch.cs#L53-L58 …
=> Support for `JsonSerialization` where `BinaryFormatter` is not supported in .NET 5.0+

Harmony/Internal/HarmonySharedState.cs
`Harmony.GetMethodFromStackframe` fails hard when encountering generics, as `FindReplacement` tries to JIT-compile and get the native address of an uninstantiated generic.
This PR makes `FindReplacement` check the stack frame's method address if possible for generic methods instead.
=> Don't JIT-compile generic methods in FindReplacement

Harmony/Internal/MethodPatcher.cs
When creating a replacement for methods which end in `throw`s, Harmony currently doesn't check if the method actually ends in a `ret` or `throw` and ends up emitting invalid `stloc`s and `ldloc`s. This PR fixes that.
A good example of the previously invalid IL can be seen in #458. This PR **won't** fix the entirety of #458 though, as this only affects the invalid IL seen there, not compatibility with "protected assemblies" in general.
=> Don't emit stloc ldloc resultVariable in methods ending in throws

Harmony/Public/Harmony.cs
Unpatch eventually calls into Patch.Remove, where the logic checks for `"*"` as the "remove all" wildcard, not null, which is the current default of Unpatch.
=> Fix Unpatch default parameter

Harmony/Tools/SymbolExtensions.cs
Use complex LambdaExpression walking to allow  `GetMethodInfo (() => myMethod)` rather than `GetMethodInfo(() => myMethod(null,null,null....))`
Quality of life improvement.    Right now manual patching is a bit annoying to pass complex method replacements to, especially when you have ref variables as for a method like:
`private static bool prePatchSomething(ref string something, ref bool correct, ref Assembly loaded, ref MyClass __result, String info, int howLong)`
you need to do something like
```
string s1=null;
bool b1=false;
Assembly a1=null;
MyClass m1 = null;
SymbolExtensions.GetMethodInfo(() => prePatchSomething(ref s1, ref b1, ref a1, ref m1, null, 0);
```
With this change:
`SymbolExtensions.GetMethodInfo(prePatchSomething);`
I believe this should be safe.  Might even technically …
=> SymbolExtensions.GetMethodInfo allow parameterless method decoding

Harmony/Documentation/articles/patching-transpiler-codes.md, Harmony/Public/ExceptionBlock.cs
This PR mentions that filter blocks are currently unsupported in the CodeInstruction article and the ExcpetionBlockType API page.
=> Mention that filter blocks are unsupported in the documentation

Harmony/Public/CodeInstruction.cs, Harmony/Tools/CodeMatch.cs, Harmony/Tools/Extensions.cs
Adds these extension methods on CodeInstruction:
- LocalIndex, which returns the operand of any ldloc/ldloca/stloc, even the short forms or the fixed forms (i.e. ldloc.s or ldloc.1)
- ArgIndex, which does the same but for ldarg/ldarga/starg
Adds these static helper methods to CodeInstruction:
- LoadLocal, which allows you to produce an optimal load from an index, optionally loading the address
- StoreLocal, which allows you to produce an optional store to an index
- LoadArg, which allows you to produce an optimal load from an argument, optionally loading the address
- StoreArg, which allows you to produce an optimal store to an argument
All of the methods are annotated with doc comments and include links to their counterparts via `<seealso>` references.
Please let me know if I got the …
=> Methods for getting indices and making loads and stores

Harmony/Documentation/articles/patching.md
Somehow there isn't any example for this so here is my proposed one.
=> Add an example for patch factory methods

Harmony/Documentation/articles/annotations.md, Harmony/Documentation/articles/basics.md, Harmony/Public/Attributes.cs, Harmony/Public/Harmony.cs, Harmony/Public/HarmonyMethod.cs, Harmony/Public/PatchClassProcessor.cs
This change adds the following features:
- `[HarmonyPatchCategory(string category)]` attribute, applied to patch container classes to specify one category for a patch
- `Harmony.PatchCategories(string category)` method, called to apply all patch container classes marked with a specific category 
-  `Harmony.PatchAllUncategorized()` method, called to apply any patch container classes not marked with a specific category
- Documentation for the above functionality (in markdown form - not sure if I have to do anything for page generation)
This functionality allows applying different sets of patches at different times when using annotated patch classes. This allows for easy conditional patch application, allowing things like delaying a patch until after a static initializer has run, or …
=> Add Categories feature to Patch Container Classes

Harmony/Internal/PatchTools.cs, Harmony/Public/Attributes.cs, Harmony/Tools/AccessTools.cs
As the title says. This is particularly interesting for targeting an `async` method with a transpiler, whether using Attributes or manually finding it with the added `AsyncMoveNext` method in AccessTools.
I'm not sure where the tests should go / how they should look, but I did test it on a game that I write mods for.  
Works perfectly, although trying to use `IAsyncStateMachine` as the type for the `__instance` parameter causes a `FormatException` for invalid IL on the call to the patch method (that took a while to figure out).
=> Adds support for targeting an async method's internal MoveNext method

Harmony/Internal/PatchTools.cs, Harmony/Tools/AccessTools.cs
This makes `MethodType`s `Getter` and `Setter` target indexer properties when used without a name.  
Type parameters are respected to target overloaded indexers.
Adds indexer specific versions of the Property methods to AccessTools, which take the containing Type and optional parameters.
=> Add targeting of indexer properties

Harmony/Public/HarmonyMethod.cs
Adds constructor overloads for `Delegate` instead of `MethodInfo` and adds implicit casts from both.
=> Add Delegate overloads and implicit casts to HarmonyMethod; Fixes #505

Harmony/Harmony.csproj
Just as we discussed, this adds support for using the netstandard2.0 target as a reference assembly.
The location of the reference assembly is in `/ref` instead of the standard `/lib` in the NuGet, so it won't ever be copied to the output path, avoiding any issues with the reference assembly being used as full fledged library in an unknown runtime implementation (.net core / .net framework)
The interesting thing is, we can ignore any IDE errors that are not related to the Public API (e.g. missing `DefinePInvokeMethod` and `CreateType` methods). Any implementation level compile errors do not matter.
=> Added netstandard2.0 reference assemblies support

Directory.Build.props, Harmony/Internal/HarmonySharedState.cs, Harmony/Public/Harmony.cs
This fixed some cases when Harmony couldn't return the original method for a patch method
Also updated the  MonoMod
=> Using `PlatformTriple.Current.GetIdentifiable` for a user submitted MethodInfo

Harmony/Documentation/articles/patching-auxilary.md
Just adding some additional language about null/zero results here, [as discussed on Discord here](https://discord.com/channels/131466550938042369/361891646742462467/1145420417838895144).
=> Add null/zero return clarifcations for TargetMethod/s

Harmony/Documentation/articles/intro.md
Just a small typo in this sentence:
> Harmony uses a variation of hooking and **focuces** only on runtime changes that don't affect files on disk:
It should read like this:
> Harmony uses a variation of hooking and **focuses** only on runtime changes that don't affect files on disk:
Thank you for this library! Merry Christmas and happy New Year 🎊
=> Fix typo in intro.md

Harmony/Internal/InlineSignatureParser.cs
Currently, Harmony can't patch nor `MethodCopier.GetInstructions` of methods with `calli` instructions containing generic instances in their signature such as in this example:
```
calli void(class [mscorlib]System.Collections.Generic.List`1<int>)
```
Patching or calling `GetInstructions` on such methods results in:
```
System.NotSupportedException: Unsupported generic callsite element: GenericInstance
```
This is a rare but legitimate case that's come up in something I'm working on. Note that this isn't about open generics (like `List<T>`, which Harmony doesn't really support) but closed ones (e.g. `List<int>`).
The pull request fixes this issue by adding support for type signature elements of kind `GenericInstance` in the inline signature parser. The patch is directly based on …
=> Support GenericInstance types in inline method signatures

Harmony/Documentation/articles/patching-injections.md, Harmony/Extras/RefResult.cs, Harmony/Internal/MethodPatcher.cs, HarmonyTests/Patching/Assets/Specials.cs, HarmonyTests/Patching/Specials.cs
It is, on the whole, a suggestion. Currently, there is no way to override the reference itself in a method like `ref T fn()`
This implementation adds an optional parameter `out RefResult<T> __resultRef` (`out` is a requirement as it is called immediately after the patch and nulled), where `delegate ref T RefResult<T>()`
I don't have a user-case for this, but someone might have one
// On second thought, `out` requirement is unnecessary, `ref` is okay
=> Way to override returned reference itself

Harmony/Internal/MethodPatcher.cs, HarmonyTests/Patching/Assets/Specials.cs, HarmonyTests/Patching/Specials.cs
Pretty simple fix, as title says
=> Fix prefix skipping for dead-end code

Harmony/Harmony.csproj, ILRepack.targets
* for Thin they are embedded
* for Fat they are portable
Removed snupkg generation, the .pdb files are included in the nupkg
Side fix:
Exclude the secondary System.Reflection.* packages from NuGet - we were adding new dependencies that we don't really need
=> Added pdb generation

Harmony/Harmony.csproj
Corrections based on the feedback:
* Exclude pdb copy from NuGet packages for thin
* Thin now includes the debug symbols as portable
* Always exclude the .dll/pdb/xml files of the dependencies after Pack
=> Added pdb generation  2

.github/workflows/test.yml, Harmony.sln, Harmony/Harmony.csproj
* Added a `Lib.Harmony.Ref` package for netstandard2.0 reference assemblies
* Simplified the netstandard2.0 handling in Fat and Thin
=> Moved ref/netstandard2.0 into Lib.Harmony.Ref

Harmony/Harmony.csproj, ILRepack.targets
ILRepack usually resolves framework assemblies from the dotnet SDK directories if the corresponding .NET Core version is installed. If it's not installed, let's download Microsoft.NetCore.App.Ref NuGet package (equivalent of Microsoft.NETFramework.ReferenceAssemblies but for Core) of the specified version and pass the path to ILRepack so it can find the .dlls there.
Confirmed this fixes the build.
=> Ensure build works when .NET Core 3.1 or 5.0 is not installed

.github/workflows/test-build.yml, Harmony/Harmony.csproj, packages/.gitignore
Taken from BepInEx, it's atrocious how badly `RestoreAdditionalProjectSources` is documented
=> Use the local ReleaseRef package for easier releasing

Harmony/Documentation/articles/patching-transpiler-matcher.md, Harmony/Documentation/articles/toc.md, Harmony/Documentation/examples/patching-transpiler-codematcher.cs
Why this addition to the documentation?
I discovered that many developers using Transpiler did not know the existence of the codematcher. Adding exemple will add visibility to this tool.
=> Add Code Matcher exemple to the documentation

Directory.Build.props, HarmonyTests/IL/TestMethodBodyReader.cs
This PR address the issue with Harmony when running under .NET 9. As @tyb-dev pointed out, .NET 9 changed LocalBuilder from `sealed partial class` to `abstract class`. Due to this, `MonoMod.Core` on `1.2.1` was failing because it was attempting to create an instance of LocalBuilder, resulting in the following:
```
System.MemberAccessException : Cannot create an instance of System.Reflection.Emit.LocalBuilder because it is an abstract class.
```
`MonoMod.Core` was updated to `1.2.2` roughly six days ago to address this update to `LocalBuilder`. Updating the package reference to `1.2.2` addresses this issue with Harmony, and all tests are now passing. There was one test that required an update due to type checking for `LocalBuilder` (now `RuntimeLocalBuilder` when on .NET 9).
=> update MonoMod.Core to 1.2.2 to address net9 issue

Harmony/Internal/PatchTools.cs
Fix #638 by preventing the NullReferenceException in PatchTools.GetOriginalMethod that wasn't expected by the calling code
=> Fix #638 by preventing the NullReferenceException

Harmony/Tools/AccessTools.cs, HarmonyTests/Tools/TestAccessTools.cs
This changes `AccessTools.MethodDelegate` to let you use `object` where a value type exists
Also lets you use `ref` for the first argument with value types, since currently you can't mutate structs from dynamic methods generated when open instance without boxing, so this lets you use delegates such as `void MyFunc(ref UnityEngine.Resolution res);`
=> MethodDelegate: allow for swapping value type with object, and allow ref for arg 0 on value type

Harmony/Internal/PatchTools.cs, Harmony/Tools/AccessTools.cs
Allows patch attributes like `[HarmonyPatch(typeof(TargetType), "", MethodType.Getter)]` on a method, or
```cs
[HarmonyPatch(typeof(TargetType))]
static class PatchClass
{
[HarmonyPatch("", MethodType.Getter)]
static void Postfix() { }
}
```
to target an Indexer for example. With just `null` instead of `""`, the second example would be ambiguous.
This may allow making the targeting "nameless" members like (static) constructors or indexers more explicit, by allowing to provide an empty string in addition to the MethodType or `null`. Now that I'm writing this, it seems almost unnecessary, but the idea came while [talking about possible Analyzers for HarmonyPatch attributes](https://discord.com/channels/131466550938042369/674571535570305060/1278776582797918310)
For the AccessTools methods, …
=> Allows empty string for targeting special MethodType options and doesn't try searching for it with AccessTools

Harmony/Documentation/articles/patching-transpiler-matcher.md
`![note]` inside patching-transpiler-matcher does not display correctly.
when I wrote the article I forgot to add
```md
[note]: https://raw.githubusercontent.com/pardeike/Harmony/master/Harmony/Documentation/images/note.png
```
I thought I had to deal with the `![note]` of [docfx](https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#alerts).
I added the link to the image and it's now fix.
=> fix patching-transpiler-matcher note image

Harmony/Internal/MethodCopier.cs
I was trying to patch methods in the `GL` class from opentk and it jumped to this line in code when running in debug mode. It looks like there is a leftover `Debugger` break and logging. Harmony is able to patch the method without issue other than this.
=> remove debugger log

Harmony/Internal/MethodPatcher.cs
Discussion started here: https://discord.com/channels/131466550938042369/361891646742462467/1357738423535796244
A small reproduceable sample code is seen here (as a UnityModManager mod)
I added a fix and a test.
Note: I could ***only*** reproduce on the Unity Mono runtime. Testing on .NET or .NET Framework (at least the versions I tried) didn't produce the error under the same conditions.
See test case in #658
=> Fix using __args argument on a patch targetting a method with an out bool parameter to fail on the Unity Mono platform

HarmonyTests/Patching/Arguments.cs, HarmonyTests/Patching/Assets/ArgumentCases.cs
=> Add Test Case for  #657

HarmonyTests/Patching/Arguments.cs, HarmonyTests/Patching/Assets/ArgumentCases.cs
Related: #657
Currently, the following types are definitely causing issues (Unity Mono): `char`, `nint`, `nuint`, `decimal` and enums longer than I4
=> Add more tests concerning usage of __args array with various types of out parameters

Harmony/Internal/MethodPatcher.cs
Tests are in #659
I added a separate default case just in case the enum gets new entries in the future.
=> Fix usage of __args array with various types of out parameters

Harmony/Internal/MethodCreator.cs
Fix different patches using 
```cs
ref SomeType __state
```
and 
```cs
SomeType __state
```
on the same method causing InvalidProgramException in .NET 6
=> Fix different patches using  ref SomeType __state  and SomeType __state causing InvalidProgram in .NET6+

HarmonyTests/ReversePatching/Assets/ReversePatches.cs
For some reason the targetted method now uses an implicit string[] => ReadOnlySpan<string> conversion on .NET 9 (which it didn't do before the refactor). The Transpiler fails to find a valid match because of that which results in invalid IL
=> Fix Reverse Patch Test failing. 

.github/workflows/test-build.yml, .github/workflows/test-qemu-dotnet.yml, .github/workflows/test-qemu-mono.yml, .github/workflows/test-result-upload.yml, .github/workflows/test-unix-dotnet.yml, .github/workflows/test-unix-mono.yml, .github/workflows/test-windows-dotnet.yml, .github/workflows/test-windows-framework.yml, .github/workflows/test-windows-mono.yml, .github/workflows/test.yml
- limit build job matrix to Ubuntu only
- show OS and arch directly in test labels
- `bash test.sh` *(fails: dotnet: command not found)*
=> Simplify CI labels

HarmonyTests/Tools/TestAccessTools.cs, HarmonyTests/Tools/TestAccessToolsExtensions.cs
- add test ensuring TypeSearch cache invalidation works
- add new test file for AccessTools extension helpers
- `dotnet test HarmonyTests/HarmonyTests.csproj --framework net9.0 --runtime linux-x64 --no-build --filter "FullyQualifiedName~Test_AccessTools_TypeSearch_CacheInvalidation|FullyQualifiedName~Test_AccessToolsExtensions" --logger "console;verbosity=minimal"`
=> Add missing tests for AccessTools cache and extensions

Harmony/Tools/Extensions.cs
Problem: When calling `CodeInstructionExtensions.LocalIndex`, sometimes the operand is a LocalBuilder, currently the code does not handle this.
I came across this when I was trying to get the local index from a Stloc_S but the operand was not an int but actually a LocalBuilder. In that case you need to convert operand to LocalBuilder and take the LocalIndex from it. It makes sense for this extension to do this otherwise you need to do it yourself outside.
=> Add LocalBuilder checks to `CodeInstructionExtensions.LocalIndex`

Harmony/Internal/MethodCreatorTools.cs, Harmony/Tools/FileLog.cs
Start of discussion on the discord server: https://discord.com/channels/131466550938042369/361891646742462467/1407848296734789822
Cecil's VariableDefinition was public in one FileLog method, so making that internal is the easiest fix.
The method could also be moved from FileLog to the MethodCreatorTools class, which is the only one that uses it, though.
With this change, everything Cecil is internal again:
=> Fix a bunch of Mono.Cecil's API being public in the merged version

Harmony/Public/Harmony.cs, HarmonyTests/Patching/CategoryPatches.cs
The current implementation used in Harmony scans, for each call, every type in the assembly.
This implementation creates a cache for all categories on the first call for each assembly (using a ConditionalWeakTable per Assembly)
The cache for an assembly is basically a Dictionary<string, List<Type>>, where string is the category and List<Type> is the list of types that have the attribute applied.
Considering the caches are keyed to a specific assembly; I think things like dynamic types shouldn't cause any issues. 
I'm unsure of where to put the static AssemblyCachedCategories. It's currently a static field on Harmony; but maybe it should go to the HarmonySharedState instead?
=> Improve PatchCategory/UnpatchCategory
